# Bases de dados

A seguir, documentamos o processo de extração de dados e contrução das bases.

## IBGE

Do portal Sidra, do IBGE, baixamos dados de saneamento básico, abastecimento de água, ocupação de domicílios e população total referentes ao Censo de 2010.

Para facilitar e melhor documentar a importação dos dados, baixamos os dados a partir da API do portal Sidra com o auxílio do pacote `sidrar`.

A página [http://api.sidra.ibge.gov.br/](http://api.sidra.ibge.gov.br/) pode (e deve) ser utilizada para buscar os parâmetros disponíveis de cada uma das tabelas.

O script em R utilizado para importação e limpeza dos dados pode ser encontrado [aqui](https://github.com/openvironment/ods6/blob/main/data-raw/ibge.R).

### Saneamento

Página: https://sidra.ibge.gov.br/tabela/1394

Variáveis de interesse:

- Código do município 
- Nome do município
- Número de municípios permanentes ocupados servidos por fossa


### Abastecimento

Página: https://sidra.ibge.gov.br/tabela/3217

Variáveis de interesse:

- Código do município 
- Nome do município
- Número de Municípios permanentes ocupados abastecidos por poço e mina, localizados na propriedade

### População total

Páginas: https://sidra.ibge.gov.br/tabela/200

Variáveis de interesse:

- Código do município 
- Nome do município
- Número de municípios ocupados permanentes
- População Total

## IDH

Os dados para IDH de 2010 foram baixados do portal do Atla de Desenvolvimento humano no Brasil: [http://www.atlasbrasil.org.br/acervo/biblioteca](http://www.atlasbrasil.org.br/acervo/biblioteca).

Foi feito o download da base *Censo Demográfico (1991, 2000 e 2010)*. Do arquivo *Atlas 2013_municipal, estadual e Brasil.xlsx*, foram extraídas as seguintes variáveis para o ano de 2010:

- Código do município
- IDH
- IDHE (educação)
- IDHL (longevidade)
- IDHR (renda)

O script em R utilizado para importação e limpeza dos dados pode ser encontrado [aqui](https://github.com/openvironment/ods6/blob/main/data-raw/idh.R).

## SEADE

O SEADE é o portal de estatísticas do Estado de São Paulo. É fundação vinculada à Secretaria de Governo, com o objetivo de produzir e disseminar análises e estatísticas socioeconômicas e demográficas.

Os dados estão disponibilizados [neste portal](http://produtos.seade.gov.br/produtos/projpop/index.php). Foi possível fazer o download completo da base a partir deste link: [http://produtos.seade.gov.br/produtos/projpop/download/Projpop.zip](http://produtos.seade.gov.br/produtos/projpop/download/Projpop.zip). O dicionário de variáveis pode ser baixado diretamente a partir do link [http://produtos.seade.gov.br/produtos/projpop/download/Dicionario.zip](http://produtos.seade.gov.br/produtos/projpop/download/Dicionario.zip).

Buscamos as seguintes variáveis:

- Código do município
- Ano
- Projeção População Total 
- Projeção do número de domicílios permanentes ocupados (anos 2011 a 2017)

O script em R utilizado para importação e limpeza dos dados pode ser encontrado [aqui](https://github.com/openvironment/ods6/blob/main/data-raw/seade.R).

## SNIS

O Sistema Nacional de Informações Sobre Saneamento (SNIS) possui bases de dados com informações e indicadores sobre a prestação de serviços de Água e Esgotos, Manejo de Resíduos Sólidos Urbanos e Drenagem e Manejo das Águas Pluviais Urbanas.

No portal [http://app4.mdr.gov.br/serieHistorica](http://app4.mdr.gov.br/serieHistorica), buscamos as bases com as seguintes variáveis:

- Código do prestador
- Nome do Prestador
- Natureza jurídica do prestador
- AG002  - quantidade de ligações ativas de água
- AG004 - quantidade de ligações ativas de água micromedidas
- AG008 - volume de água micromedido
- AG010 - volume de água consumido
- AG012 - volume de água macromedido
- AG013 - quantidade de economias residenciais ativas de água
- AG014 - quantidade de economias ativas micromedidas
- ES006 - volume de esgoto tratado
- ES008 - quantidade de economias residenciais ativas de esgoto
- FN001 - receita operacional direta total
- FN002 - receita operacional direta de água
- FN015 - despesas de exploração (DEX)
- AG011 - volume de água faturado
- AG018 - volume de água tratada importado
- AG019 - volume de água faturado exportado

Para isso, fizemos a seguinte busca no portal:

- No menu Água e Esgoto, selecionamos a opção **Informações e indicadores desagregados**. 

- Nos filtros, utilizamos:
    - Ano de referência: todos
    - Abrangência: todos
    - Tipo de serviço: todos
    - Natureza jurídica: todos
    - Região: sudeste
    - Estado: São Paulo
    
- Nas colunas, selecionamos:
    - Família de informações e indicadores: informações financeiras, informações de água e informações de esgoto.
    - Informações e indicadores: todos (91 selecionados)
    
Foi então baixado um arquivo CSV.

**Nota**: para ler a base, foi preciso abrir o arquivo .csv baixado do SNIS com o programa Numbers (iOS) e então exportar para Excel. Possível causa: o arquivo CSV era um arquivo binário.

O script utilizado para importação e limpeza da base por ser encontrado [aqui](https://github.com/openvironment/ods6/blob/main/data-raw/snis.R).


## Base de indicadores

Por fim, criamos a base final utilizada na construção do dashboards. Essa base é constuída pela junção das informações das bases descritas nas seções anteriores, mas principalmente pelos indicadores descritos no próximo capítulo.

O script em R utilizado para a junção das bases se encontra [aqui](https://github.com/openvironment/ods6/blob/main/data-raw/base_indicadores.R).

A seguir disponibilizamos links para o download direto da base de indicadores:

- [versão CSV](https://github.com/openvironment/ods6/raw/main/data-raw/base_indicadores.csv)
- [versão Excel](https://github.com/openvironment/ods6/raw/main/data-raw/base_indicadores.xlsx)

